import { useState } from 'react';
import { Calendar, ChevronDown, ChevronUp, BookOpen, CheckSquare } from 'lucide-react';

const Roadmap = ({ analysisData }) => {
  const [activeAccordion, setActiveAccordion] = useState(0);

  if (!analysisData || !analysisData.roadmap) {
    return (
      <div className="card" style={{ textAlign: 'center', padding: '40px' }}>
        <Calendar size={48} color="var(--text-dimmed)" style={{ marginBottom: '16px' }} />
        <h2>No Active Roadmap</h2>
        <p style={{ color: 'var(--text-muted)', marginTop: '8px' }}>
          Please go to the <strong>Dashboard</strong>, upload a resume, and run the profile analysis first.
        </p>
      </div>
    );
  }

  const toggleAccordion = (idx) => {
    setActiveAccordion(activeAccordion === idx ? null : idx);
  };

  const renderResource = (res) => {
    const urlRegex = /(https?:\/\/[^\s)]+)/g;
    const parts = res.split(urlRegex);
    return parts.map((part, i) => {
      if (part.match(urlRegex)) {
        return (
          <a 
            key={i} 
            href={part} 
            target="_blank" 
            rel="noopener noreferrer" 
            style={{ 
              color: 'var(--accent-primary)', 
              textDecoration: 'underline',
              wordBreak: 'break-all',
              fontWeight: '500'
            }}
          >
            {part}
          </a>
        );
      }
      return part;
    });
  };

  return (
    <div className="roadmap-view">
      <div style={{ marginBottom: '32px' }}>
        <h1 style={{ fontSize: '32px', marginBottom: '10px' }}>Personalized Learning Roadmap</h1>
        <p style={{ color: 'var(--text-muted)', fontSize: '16px' }}>
          A tailored milestone path generated by the Roadmap Agent to help you acquire missing competencies for the <strong>{analysisData.target_role}</strong> role.
        </p>
      </div>

      <div className="card" style={{ padding: '32px' }}>
        <h2 style={{ fontSize: '24px', marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '12px' }}>
          <BookOpen size={24} color="var(--accent-primary)" /> Curated Learning Phases
        </h2>
        
        <div className="roadmap-timeline" style={{ borderLeft: '2px solid rgba(255, 255, 255, 0.08)', paddingLeft: '32px' }}>
          {analysisData.roadmap.map((phase, idx) => {
            const isOpen = activeAccordion === idx;
            return (
              <div key={idx} className="roadmap-step" style={{ marginBottom: '16px' }}>
                <div 
                  className="roadmap-header" 
                  onClick={() => toggleAccordion(idx)}
                  style={{ padding: '20px', borderRadius: '10px' }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                    <span style={{ 
                      fontSize: '14px', 
                      fontWeight: '700', 
                      background: 'rgba(14, 165, 233, 0.15)', 
                      color: 'var(--accent-primary)',
                      padding: '6px 12px',
                      borderRadius: '6px'
                    }}>
                      Month {idx + 1}
                    </span>
                    <h3 style={{ fontSize: '20px', fontWeight: '700' }}>{phase.month}</h3>
                  </div>
                  {isOpen ? <ChevronUp size={22} /> : <ChevronDown size={22} />}
                </div>
                
                {isOpen && (
                  <div className="roadmap-body" style={{ padding: '24px', borderRadius: '0 0 10px 10px' }}>
                    <div className="grid-2" style={{ gap: '32px' }}>
                      <div>
                        <h4 style={{ fontSize: '18px', marginBottom: '16px', color: 'var(--text-main)', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: '600' }}>
                          <CheckSquare size={18} color="var(--success)" /> Key Study Topics
                        </h4>
                        <ul style={{ display: 'flex', flexDirection: 'column', gap: '12px', paddingLeft: '20px', fontSize: '16px' }}>
                          {phase.topics?.map((topic, tIdx) => (
                            <li key={tIdx} style={{ color: 'var(--text-muted)', lineHeight: '1.5' }}>{topic}</li>
                          ))}
                        </ul>
                      </div>
                      
                      <div>
                        <h4 style={{ fontSize: '18px', marginBottom: '16px', color: 'var(--text-main)', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: '600' }}>
                          <BookOpen size={18} color="var(--accent-primary)" /> Recommended Learning Assets
                        </h4>
                        <ul style={{ display: 'flex', flexDirection: 'column', gap: '12px', paddingLeft: '20px', fontSize: '16px' }}>
                          {phase.resources?.map((res, rIdx) => (
                            <li key={rIdx} style={{ color: 'var(--text-muted)', lineHeight: '1.5' }}>
                              {renderResource(res)}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default Roadmap;
